USE university;

INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Juan','Infante','juaninfante@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('David','Serna','davidserna@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Josefa','Pedraza','josefapedraza@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Antonio','Belda','antonioBelda@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Luis','Balmori','luisbalmori@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Francisco','Usategui','franciscousategui@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Ana Maria','Bocigas','anabocigas@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Carlos','Fuertes','carlosfuerte@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Daniel','Aguado','danielaguado@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Maria Pilar','Espino','pilarespino@university.com');

INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Miguel','Carulla','miguelcarulla@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Ana','Calderon','anacalderon@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Dolores','Espino','doloresespino@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Pedro','Sobreira','pedrosobreira@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Alejandro','Bueno','alejandrobueno@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Carmen','Pino','carmenpino@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Josefa','Villena','josefavillena@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Jose','Bonilla','josebonilla@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Aitor','Matos','aitormatos@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('June','Merchan','junemerchan@university.com');

INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Iñaki','Nadal','iñakinadal@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Ester','Jerez','esterjerez@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Jose Pablo','Agudo','pabloagudo@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Guadalupe','Prats','guadalupeprats@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Nicolas','Martin','nicolasmartin@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Jenifer','Gomez','jenifergomez@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Moises','Palacio','moisespalacio@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Yolanda','Fonseca','yolandafonseca@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Hugo','Parada','hugoparada@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Yago','Salas','yagosalas@university.com');

INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Inmaculada','Santamaria','inmasantamaria@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Lucas','Puig','lucaspuig@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Susana','Medrano','susanamedrano@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Juan Carlos','Cervantes','juancarcervantes@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Imanol','Arias','imanolarias@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Anabel','Vazquez','anabelvazquez@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Gael','Figueroa','gaelfigueroa@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Rosario','Salvador','rosariosalvador@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Aimar','Hoyos','aimarhoyos@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Alejandra','Galiano','alejandragaliano@university.com');

INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Leonor','Freire','leonorfreire@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Bilal','Navas','bilalnavas@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Claudia','Fuertes','claudiafuertes@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Maximo','Fernandez','maximofernandez@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Luisa','Costas','luisacostas@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Marcos','Almagro','marcosalmagro@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Gloria','Olmo','gloriaolmo@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Emiliano','Rio','emilianorio@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Mercedes','Corrales','mercedescorrales@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Omar','Castaño','omarcastaño@university.com');

INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Leticia','Nieto','leticianieto@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Angelina','Botella','angelinabotella@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Axel','Soler','axersoler@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Laia','Camacho','laiacamacho@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Mateo ','Gisbert','mateogisbert@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Obdulia','Bonilla','obduliabonilla@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Marti','Goñi','martigoñi@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Claudia','Villanueva','claudiavillanueva@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Juiana','Atienza','julianaatienza@university.com');
INSERT INTO students(students_first_name,students_last_name,students_email) VALUES('Imanol','Bartolome','imanolbartolome@university.com');

INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Manuel','Nevado','manuelnevado@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Rafael','Figueroa','rafaelfigueroa@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Teresa','Valderrama','teresavalderrama@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Daniel','Bejarano','danielbejarano@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Jesus','Cerezo','jesuscerezo@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Francisco','Aguilera','franciscoaguilera@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Carolina','Guillen','carolinaguillen@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Isabel','Chaves','isabelchaves@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Javier','Exposito','javier exposito@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Diego','Casanova','diego casanova@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Mateo','Fernandez','mateofernandez@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Vanesa','Lucena','vanesalucena@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Roberto','Hurtado','robertohurtado@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Anais','Padron','anaispadron@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Santiago','Molina','santiagomolina@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Candido','Perea','candidoperea@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Julia','Roca','juliaroca@university.com');
INSERT INTO professors(professors_first_name,professors_last_name,professors_email) VALUES('Jose Angel','Perez','joseanperez@university.com');

INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Bases de datos', 1);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('JavaScript', 1);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Programación en Java', 1);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Lenguaje de marcas', 1);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('HTML y HTML5', 2);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('CSS y SCSS', 2);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Control numérico', 2);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Formación y orientación laboral', 3);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Programación orientada a objetos', 3);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Programación PLC', 4);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Informática aplicada', 4);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Cálculo infinitesimal', 4);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Algebra', 5);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Análisis y diseño de añgoritmos', 5);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Física', 5);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Estadística', 5);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Matemáticas', 6);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Diseño gráfico', 6);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Fundamentos de informática', 7);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Electricidad y electrónica', 7);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Fundamentos de ingeniería', 8);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Organización y gestión de empresas', 8);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Fundamentos de los computadores', 8);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Metodología de la programación', 9);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Python', 9);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('React JS', 9);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Ingeniería de software', 10);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Tecnología de la información', 10);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Innovación en entornos digitales', 10);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Sistemas de información en una empresa', 10);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Robótica', 11);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Ofimática', 11);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Desarrollo web', 12);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Inteligencia artificial', 12);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Sistemas digitales', 13);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Algoritmos y estrucuturas de datos', 13);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Probabilidades y estadística', 14);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Estrucutura de computadores', 14);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Sistemas operativos', 14);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Fundamentos de economía', 15);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Administración de empresas', 15);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Ciberseguridad', 16);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Sistemas orientados a servicios', 16);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Informática industrial', 16);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Investigación operativa', 16);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Middleware', 16);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Procesamiento digital de la señal', 17);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Sistemas inteligentes', 17);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Traductores de lenguajes', 17);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Optimización heurística', 18);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Programming Project', 18);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Nanotecnología', 18);
INSERT INTO courses(courses_name,courses_professors_id) VALUES ('Reconocimiento de formas', 18);

INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (1, 1, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (1, 2, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (1, 3, 6.5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (1, 4, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (1, 5, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (2, 2, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (2, 3, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (2, 4, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (2, 5, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (2, 6, 8.75);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (3, 3, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (3, 4, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (3, 5, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (3, 6, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (3, 7, 7.5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (4, 4, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (4, 5, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (4, 6, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (4, 7, 6.4);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (4, 8, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (5, 5, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (5, 6, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (5, 7, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (5, 8, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (5, 9, 8.75);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (6, 6, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (6, 7, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (6, 8, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (6, 9, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (6, 10, 6.5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (7, 7, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (7, 8, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (7, 9, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (7, 10, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (7, 11, 10);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (8, 8, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (8, 9, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (8, 10, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (8, 11, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (8, 12, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (9, 9, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (9, 10, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (9, 11, 7.75);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (9, 12, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (9, 13, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (10, 10, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (10, 11, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (10, 12, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (10, 13, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (10, 14, 8.8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (11, 11, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (11, 12, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (11, 13, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (11, 14, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (11, 15, 10);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (12, 12, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (12, 13, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (12, 14, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (12, 15, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (12, 16, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (13, 13, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (13, 14, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (13, 15, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (13, 16, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (13, 17, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (14, 14, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (14, 15, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (14, 16, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (14, 17, 8.3);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (14, 18, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (15, 15, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (15, 16, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (15, 17, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (15, 18, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (15, 19, 9.5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (16, 16, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (16, 17, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (16, 18, 8.1);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (16, 19, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (16, 20, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (17, 17, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (17, 18, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (17, 19, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (17, 20, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (17, 21, 9.6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (18, 18, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (18, 19, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (18, 20, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (18, 21, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (18, 22, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (19, 19, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (19, 20, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (19, 21, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (19, 22, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (19, 23, 10);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (20, 20, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (20, 21, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (20, 22, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (20, 23, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (20, 24, 8.2);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (21, 21, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (21, 22, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (21, 23, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (21, 24, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (21, 25, 9.3);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (22, 22, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (22, 23, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (22, 24, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (22, 25, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (22, 26, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (23, 23, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (23, 24, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (23, 25, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (23, 26, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (23, 27, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (24, 24, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (24, 25, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (24, 26, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (24, 27, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (24, 28, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (25, 25, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (25, 26, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (25, 27, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (25, 28, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (25, 29, 9.2);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (26, 26, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (26, 27, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (26, 28, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (26, 29, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (26, 30, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (27, 27, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (27, 28, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (27, 29, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (27, 30, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (27, 31, 10);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (28, 28, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (28, 29, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (28, 30, 7.2);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (28, 31, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (28, 32, 5.7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (29, 29, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (29, 30, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (29, 31, 8.1);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (29, 32, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (29, 33, 8.2);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (30, 30, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (30, 31, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (30, 32, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (30, 33, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (30, 34, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (31, 31, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (31, 32, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (31, 33, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (31, 34, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (31, 35, 10);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (32, 32, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (32, 33, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (32, 34, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (32, 35, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (32, 36, 8.7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (33, 33, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (33, 34, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (33, 35, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (33, 36, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (33, 37, 8.25);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (34, 34, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (34, 35, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (34, 36, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (34, 37, 7.5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (34, 38, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (35, 35, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (35, 36, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (35, 37, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (35, 38, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (35, 39, 9.45);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (36, 36, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (36, 37, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (36, 38, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (36, 39, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (36, 40, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (37, 37, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (37, 38, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (37, 39, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (37, 40, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (37, 41, 9.2);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (38, 38, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (38, 39, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (38, 40, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (38, 41, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (38, 42, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (39, 39, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (39, 40, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (39, 41, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (39, 42, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (39, 43, 10);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (40, 40, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (40, 41, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (40, 42, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (40, 43, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (40, 44, 8.23);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (41, 41, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (41, 42, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (41, 43, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (41, 44, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (41, 45, 10);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (42, 42, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (42, 43, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (42, 44, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (42, 45, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (42, 46, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (43, 43, 6.5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (43, 44, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (43, 45, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (43, 46, 6.75);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (43, 47, 6.5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (44, 44, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (44, 45, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (44, 46, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (44, 47, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (44, 48, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (45, 45, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (45, 46, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (45, 47, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (45, 48, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (45, 49, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (46, 46, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (46, 47, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (46, 48, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (46, 49, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (46, 50, 10);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (47, 47, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (47, 48, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (47, 49, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (47, 50, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (47, 51, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (48, 48, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (48, 49, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (48, 50, 8.3);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (48, 51, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (48, 52, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (49, 49, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (49, 50, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (49, 51, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (49, 52, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (49, 53, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (50, 50, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (50, 51, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (50, 52, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (50, 53, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (50, 44, 6.5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (51, 51, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (51, 52, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (51, 53, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (51, 24, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (51, 25, 10);

INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (52, 1, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (52, 2, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (52, 3, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (52, 4, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (52, 5, 9.3);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (53, 1, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (53, 2, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (53, 3, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (53, 4, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (53, 5, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (54, 1, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (54, 2, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (54, 3, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (54, 4, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (54, 5, 8.2);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (55, 1, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (55, 2, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (55, 3, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (55, 4, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (55, 5, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (56, 50, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (56, 51, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (56, 52, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (56, 53, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (56, 47, 10);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (57, 49, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (57, 50, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (57, 51, 7.75);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (57, 52, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (57, 53, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (58, 49, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (58, 50, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (58, 51, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (58, 52, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (58, 53, 9.3);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (59, 49, 5);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (59, 50, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (59, 51, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (59, 52, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (59, 53, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (60, 49, 8);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (60, 50, 7);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (60, 51, 9);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (60, 52, 6);
INSERT INTO grades(grades_students_id,grades_courses_id,grades_score) VALUES (60, 53, 10);